name: Build and Sign iOS

on:
  - workflow_dispatch

jobs:
  build:
    name: Builds and signs using the repository secrets
    runs-on: macos-latest
    steps:
      - name: Do the actual build task
        uses: yukiarrr/ios-build-action@v1.12.0
        with:
          project-path: /gophermaps-ios.xcodeproj
          p12-base64: ${{ secrets.P12_BASE64 }}
          mobileprovision-base64: ${{ secrets.MOBILEPROVISION_BASE64 }}
          code-signing-identity: ${{ secrets.CODE_SIGNING_IDENTITY }}
          team-id: ${{ secrets.TEAM_ID }}
